language: python
python:
 - "3.6.6"
install:
 - pip install -r requirements.txt
sudo: required
services:
 - docker
script:
 - cd docker
 - docker exec -ti decide_web ./manage.py test
 - cd ..
notifications:
  email: false
before_install:
 - cd docker
 - docker-compose up -d
 - cd ..